apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: front-mgmt-cd
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  destination:
    server: https://kubernetes.default.svc
    namespace: project-mgmt
  sources:
    - repoURL: 'https://github.com/Pezl05/helm-template.git'
      path: service-chart
      targetRevision: main
      helm:
        valueFiles:
          - $values/helmValues.yaml
    - repoURL: 'https://github.com/Pezl05/nextjs-front-service.git'
      targetRevision: main
      ref: values