replicaCount: 1
appName: front-mgmt

image:
  repository: "harbor.pezl.local/project_mgmt/nextjs-front-service"
  tag: "latest"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 3000
  targetPort: 3000

ingress:
  enabled: true
  rewriteTarget: /
  tls:
    secretName: project-mgmt-tls
    hosts: project-mgmt.pezl.local
  host: project-mgmt.pezl.local
  paths: /
  pathType: Prefix

env:
  OTEL_RESOURCE_ATTRIBUTES: "service.name=front-service"
  OTEL_EXPORTER_OTLP_ENDPOINT: http://jaeger-collector.observability:4318
  OTEL_LOG_LEVEL: error

secret:
  AUTH_API: "http://auth-mgmt-service:3000"
  PROJECT_API: "http://project-mgmt-service:3000"
  TASK_API: "http://task-mgmt-service:3000"
  JWT_KEY: "P@ssw0rd"